# Generated by Django 5.2.5 on 2026-08-22 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fulfillment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed')], db_index=True, default='reported', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('client_reported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reports', to='accounts.device')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reports', to='fulfillment.invoice')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_confirmations', to=settings.AUTH_USER_MODEL)),
                ('return_report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='returns.returnreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='fulfillment.invoiceitem')),
                ('return_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='returns.returnreport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('return_report', 'invoice_item'), name='unique_invoice_item_per_return')],
            },
        ),
    ]
