# Generated by Django 5.2.5 on 2026-08-22 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fulfillment', '0002_invoice_invoice_total_nonnegative_and_more'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='return_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_commission__gte', 0)), name='return_item_commission_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='return_item_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('commission_total__gte', 0)), name='return_item_commission_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnreport',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='return_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnreport',
            constraint=models.CheckConstraint(condition=models.Q(('commission_total__gte', 0)), name='return_commission_nonnegative'),
        ),
    ]
