# Generated by Django 5.2.5 on 2026-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20),
        ),
    ]
