import express from 'express';
import clienteRoutes from '../routes/Cliente';
import contactoRoutes from '../routes/Contacto';
import personaRoutes from '../routes/Persona';
import vendedorRoutes from '../routes/Vendedor';
import rolRoutes from '../routes/Rol';
import usuarioRoutes from '../routes/Usuario';
import direccionRoutes from '../routes/Direccion';
import telefonoRoutes from '../routes/Telefono';
import tipoDireccionRoutes from '../routes/TipoDireccion';
import tipoTelefonoRoutes     from '../routes/TipoTelefono';
import sectorRoutes from '../routes/Sector';
import ciudadRoutes from '../routes/Ciudad';
import provinciaRoutes from '../routes/Provincia';
import tipoContactoRoutes from '../routes/TipoContacto';
import inventarioRoutes from '../routes/inventario';
import MarcaRoutes from '../routes/Marca';
import ModeloRoutes from '../routes/Modelo';
import PedidoRoutes from '../routes/Pedido';
import ProductoRoutes from '../routes/Producto';
import SuplidorRoutes from '../routes/Suplidor';
import UnidadMedidaRoutes from '../routes/UnidadMedida';
import tipoProducto from '../routes/Tipo';
import pedidoDetalle from '../routes/PedidoDetalle';
import statusPedido from '../routes/Status';
// Initialization
let router = express.Router();

// Routes
router.use('/cliente', clienteRoutes);
router.use('/persona', personaRoutes);
router.use('/contacto', contactoRoutes);
router.use('/vendedor', vendedorRoutes);
router.use('/rol', rolRoutes);
router.use('/usuario', usuarioRoutes);
router.use('/direccion', direccionRoutes);
router.use('/telefono', telefonoRoutes);
router.use('/tipoDireccion', tipoDireccionRoutes);
router.use('/tipoTelefono', tipoTelefonoRoutes);
router.use('/sector', sectorRoutes);
router.use('/provincia', provinciaRoutes);
router.use('/ciudad', ciudadRoutes);
router.use('/tipoContacto', tipoContactoRoutes);
router.use('/inventario', inventarioRoutes);
router.use('/marca', MarcaRoutes);
router.use('/modelo', ModeloRoutes);
router.use('/pedido', PedidoRoutes);
router.use('/producto', ProductoRoutes);
router.use('/suplidor', SuplidorRoutes);
router.use('/unidadMedida', UnidadMedidaRoutes);
router.use('/tipoProducto', tipoProducto);
router.use('/pedidoDetalle', pedidoDetalle);
router.use('/status',statusPedido);
export default router;