# Generated by Django 5.2.5 on 2026-08-22 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_catalog_changes(apps, schema_editor):
    sync_change = apps.get_model("sync", "SyncChange")
    for model_name, entity_type in (("Customer", "customer"), ("Product", "product")):
        model = apps.get_model("catalog", model_name)
        sync_change.objects.bulk_create([
            sync_change(entity_type=entity_type, entity_id=entity.id, version=entity.version)
            for entity in model.objects.all().iterator()
        ], ignore_conflicts=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.UUIDField()),
                ('version', models.PositiveBigIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'version'), name='unique_sync_entity_version')],
            },
        ),
        migrations.CreateModel(
            name='SyncDeviceCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('acknowledged_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sync_cursor', to='accounts.device')),
            ],
        ),
        migrations.CreateModel(
            name='SyncOperationReceipt',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=30)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('client_timestamp', models.DateTimeField()),
                ('client_version', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('conflict', 'Conflict')], db_index=True, max_length=20)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('conflict_code', models.CharField(blank=True, max_length=50)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_receipts', to='accounts.device')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.RunPython(seed_catalog_changes, migrations.RunPython.noop),
    ]
