# Generated by Django 5.2.5 on 2026-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncoperationreceipt',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], db_index=True, max_length=20),
        ),
    ]
