# Generated by Django 5.2.5 on 2026-08-22 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_business_changes(apps, schema_editor):
    sync_change = apps.get_model("sync", "SyncChange")
    sources = (
        ("sales", "Order", "order", "seller_id", "version"),
        ("fulfillment", "Invoice", "invoice", "seller_id", "version"),
        ("payments", "PaymentReport", "payment", "seller_id", "version"),
        ("returns", "ReturnReport", "return", "seller_id", "version"),
        ("payments", "CommissionMovement", "commission", "seller_id", "version"),
        ("settlements", "CommissionSettlement", "settlement", "seller_id", None),
    )
    for app_label, model_name, entity_type, seller_field, version_field in sources:
        model = apps.get_model(app_label, model_name)
        for entity in model.objects.all().iterator():
            sync_change.objects.update_or_create(
                entity_type=entity_type,
                entity_id=entity.id,
                version=getattr(entity, version_field) if version_field else 1,
                defaults={"seller_id": getattr(entity, seller_field)},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('payments', '0003_commissionmovement_version'),
        ('returns', '0001_initial'),
        ('sales', '0002_alter_order_status'),
        ('settlements', '0001_initial'),
        ('sync', '0002_alter_syncoperationreceipt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncchange',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_business_changes, migrations.RunPython.noop),
    ]
