# Generated by Django 5.2.5 on 2026-08-22 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fulfillment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('external_card_terminal', 'External card terminal')], max_length=30)),
                ('external_terminal_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed')], db_index=True, default='reported', max_length=20)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('client_reported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reports', to='accounts.device')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_report', to='fulfillment.invoice')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL)),
                ('payment_report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='payments.paymentreport')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('settled', 'Settled')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_movements', to='fulfillment.invoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_movements', to='fulfillment.invoiceitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_movements', to=settings.AUTH_USER_MODEL)),
                ('payment_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_movements', to='payments.paymentconfirmation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('movement_type', 'credit')), fields=('invoice_item',), name='unique_commission_credit_per_invoice_item')],
            },
        ),
    ]
