# Generated by Django 5.2.5 on 2026-08-22 13:10

from django.db import migrations, models


def populate_credit_references(apps, schema_editor):
    commission_movement = apps.get_model("payments", "CommissionMovement")
    for movement in commission_movement.objects.filter(reference_id__isnull=True).iterator():
        movement.reference_id = movement.payment_confirmation_id
        movement.save(update_fields=["reference_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmovement',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionmovement',
            name='reference_type',
            field=models.CharField(default='payment_confirmation', max_length=30),
        ),
        migrations.RunPython(populate_credit_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='commissionmovement',
            name='reference_id',
            field=models.UUIDField(),
        ),
    ]
