# Generated by Django 5.2.5 on 2026-08-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_commissionmovement_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmovement',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
