# Generated by Django 5.2.5 on 2026-08-22 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fulfillment', '0002_invoice_invoice_total_nonnegative_and_more'),
        ('payments', '0003_commissionmovement_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commissionmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='commission_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentreport',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_terminal_reference__isnull', True), ('method', 'cash')), models.Q(('external_terminal_reference__isnull', False), ('method', 'external_card_terminal'), models.Q(('external_terminal_reference', ''), _negated=True)), _connector='OR'), name='payment_terminal_reference_matches_method'),
        ),
    ]
