version: '3'
services:
  lottery-api:
    build: .
    ports: 
      - ${PORT}:5000
    networks:
      - traefik-network

  lottery-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - traefik-network

networks:
  traefik-network:
    external:
      name: traefik_proxynet
