# Generated by Django 5.2.5 on 2026-08-22 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_commissionmovement_reference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_ends_at', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_commission_settlements', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSettlementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_item', to='payments.commissionmovement')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='settlements.commissionsettlement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
