# Generated by Django 5.2.5 on 2026-08-22 23:05

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_commissionmovement_commission_amount_nonnegative_and_more'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsettlementitem',
            name='movement_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='settlement_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlementitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='settlement_item_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'credit'), ('signed_amount', models.F('amount'))), models.Q(('movement_type', 'debit'), ('signed_amount', django.db.models.expressions.CombinedExpression(models.F('amount'), '*', models.Value(-1)))), _connector='OR'), name='settlement_item_signed_amount_consistent'),
        ),
    ]
